ci: skip crave destroy

diff --git a/.github/workflows/selfhosted.yml b/.github/workflows/selfhosted.yml
--- a/.github/workflows/selfhosted.yml
+++ b/.github/workflows/selfhosted.yml
@@ -551,11 +551,11 @@ jobs:
       continue-on-error: true
 
       # Remove 'crave' clone
-    - name: Destroy Crave Clone
-      if: ${{ always() }}
-      run: |
-        if grep -q "$PROJECTFOLDER" <(crave clone list --json | jq -r '.clones[]."Cloned At"') || [[ "${DCDEVSPACE}" == "1" ]]; then
-          crave clone destroy -y $PROJECTFOLDER || echo "Error removing $PROJECTFOLDER"
-        else          
-          echo "Skipping removal"
-        fi
+    #- name: Destroy Crave Clone
+    #  if: ${{ always() }}
+    #  run: |
+    #    if grep -q "$PROJECTFOLDER" <(crave clone list --json | jq -r '.clones[]."Cloned At"') || [[ "${DCDEVSPACE}" == "1" ]]; then
+    #      crave clone destroy -y $PROJECTFOLDER || echo "Error removing $PROJECTFOLDER"
+    #    else          
+    #      echo "Skipping removal"
+    #    fi
